// Code generated by Wire protocol buffer compiler, do not edit.
// Source: PlatformInfoProto in platform_info.proto
package com.github.kazukinr.flutter_message_channels.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

public class PlatformInfoProto(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  public val version: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PlatformInfoProto, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  public override fun newBuilder(): Nothing = throw AssertionError()

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PlatformInfoProto) return false
    if (unknownFields != other.unknownFields) return false
    if (version != other.version) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + version.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """version=${sanitize(version)}"""
    return result.joinToString(prefix = "PlatformInfoProto{", separator = ", ", postfix = "}")
  }

  public fun copy(version: String = this.version, unknownFields: ByteString = this.unknownFields):
      PlatformInfoProto = PlatformInfoProto(version, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PlatformInfoProto> = object : ProtoAdapter<PlatformInfoProto>(
      FieldEncoding.LENGTH_DELIMITED, 
      PlatformInfoProto::class, 
      "type.googleapis.com/PlatformInfoProto", 
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(value: PlatformInfoProto): Int {
        var size = value.unknownFields.size
        if (value.version != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.version)
        return size
      }

      public override fun encode(writer: ProtoWriter, value: PlatformInfoProto): Unit {
        if (value.version != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.version)
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): PlatformInfoProto {
        var version: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> version = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PlatformInfoProto(
          version = version,
          unknownFields = unknownFields
        )
      }

      public override fun redact(value: PlatformInfoProto): PlatformInfoProto = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
